### ISSUE TITLE
Problems on the pair_coeff

### ISSUE THREAD

**Issue by Qylz** [apoorvkh/Graphene-Water-Filtration#2]
Hi. I tried to open the lammps input script for graphene water desalination. But there is an error as I have copied below. I am not sure what it means. How do I solve this?

# ------------- Coefficients ----------------
# AIREBO:
pair_coeff * * airebo CH.airebo_real C NULL NULL NULL NULL NULL C H
ERROR on proc 0: Potential file does not match AIREBO/REBO style variant (../pair_airebo.cpp:3400)
Last command: pair_coeff * * airebo CH.airebo_real C NULL NULL NULL NULL NULL C H
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

**Comment by apoorvkh** [comment]
Looks like this issue is caused by using a more recent version of LAMMPS, see:
https://lammps.sandia.gov/threads/msg81827.html

Please try downgrading to a previous version (perhaps from 2016-2017 to be safe):
https://lammps.sandia.gov/tars/
